[package]
name = "fdf"
version = "0.1.0"
edition = "2021"

[lib]
name = "fdf"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.3"
